FROM rust:alpine as builder

RUN apk add musl-dev openssl ca-certificates pkgconfig libressl-dev

RUN cargo install --version=^0.7 sqlx-cli --no-default-features --features postgres

FROM alpine

RUN apk add libressl libc6-compat

COPY --from=builder /usr/local/cargo/bin/sqlx /bin/sqlx

CMD sqlx database create && sqlx migrate run

