name: Build and Deploy Server Binary

on:
  push:
    branches:
      - main
    paths:
      - 'server/src/*'
      - 'server/src/**'
      - 'server/src/**/*'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true

    steps:

    - name: Stop server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ~/rustapps/tradecoins_gha/scripts/app_stop.sh

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build binary
      working-directory: server
      run: cargo build --release --bin tradecoins-server

    - name: Copy binary via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "server/target/release/tradecoins-server"
        target: "/home/ubuntu/rustapps/tradecoins_gha/"
        strip_components: 3
        overwrite: true

    - name: Start server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ~/rustapps/tradecoins_gha/scripts/app_start.sh

