name: Update Server Configs

on:
  push:
    branches:
      - main
    paths:
      - 'server/*'
      - 'server/**'
      - 'server/**/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy configs via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "server/configuration, server/migrations, server/scripts"
        target: "/home/ubuntu/rustapps/tradecoins_gha/"
        strip_components: 1
        overwrite: true

    - name: Run DB migrations
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/rustapps/tradecoins_gha
          ./scripts.init_db_prod.sh


